name: Node.js Package

on:
  push:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - uses: actions/checkout@v3

      - run: npm publish # --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
